name: 'Install cargo-sbom'
description: 'Generates an SBOM for a Rust/Cargo project'
inputs:
  version:
    description: 'cargo-sbom version to use'
    required: false
    default: 'latest'
  arch:
    description: 'cargo-sbom architecture'
    required: false
    default: 'x86_64'
  platform:
    description: 'cargo-sbom platform'
    required: false
    default: 'unknown-linux-gnu'
runs:
  using: "composite"
  steps:
    - run: curl -sSL https://github.com/psastras/sbom-rs/releases/download/cargo-sbom-${{ inputs.version }}/cargo-sbom-${{ inputs.arch }}-${{ inputs.platform }} -o ${{ github.action_path }}/cargo-sbom
      shell: bash
    - run: chmod +x ${{ github.action_path }}/cargo-sbom
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
